# Generated by Django 3.0.4 on 2020-03-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video',
        ),
    ]
