# Generated by Django 3.0.4 on 2020-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='user_thumbnails/'),
            preserve_default=False,
        ),
    ]
